// Code generated by protoc-gen-go. DO NOT EDIT.
// source: agentMessage.protoStruct

/*
Package agentState is a generated protocol buffer package.

It is generated from these files:
	agentMessage.protoStruct

It has these top-level messages:
	Agentstate
	Request
	Setup
*/
package protoStruct

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the protoStruct package it is being compiled against.
// A compilation error at this line likely means your copy of the
// protoStruct package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the protoStruct package

// Regular message, that is sent on heartbeat
type Agentstate struct {
	Token        string `protobuf:"bytes,1,opt,name=token" json:"token,omitempty"`
	UserID       string `protobuf:"bytes,2,opt,name=userID" json:"userID,omitempty"`
	AgentID      string `protobuf:"bytes,3,opt,name=agentID" json:"agentID,omitempty"`
	ProductID    string `protobuf:"bytes,4,opt,name=productID" json:"productID,omitempty"`
	Weight       int32  `protobuf:"varint,5,opt,name=weight" json:"weight,omitempty"`
	StateExpires int32  `protobuf:"varint,6,opt,name=stateExpires" json:"stateExpires,omitempty"`
}

func (m *Agentstate) Reset()                    { *m = Agentstate{} }
func (m *Agentstate) String() string            { return proto.CompactTextString(m) }
func (*Agentstate) ProtoMessage()               {}
func (*Agentstate) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Agentstate) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *Agentstate) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *Agentstate) GetAgentID() string {
	if m != nil {
		return m.AgentID
	}
	return ""
}

func (m *Agentstate) GetProductID() string {
	if m != nil {
		return m.ProductID
	}
	return ""
}

func (m *Agentstate) GetWeight() int32 {
	if m != nil {
		return m.Weight
	}
	return 0
}

func (m *Agentstate) GetStateExpires() int32 {
	if m != nil {
		return m.StateExpires
	}
	return 0
}

type Request struct {
	AgentID string `protobuf:"bytes,1,opt,name=agentID" json:"agentID,omitempty"`
}

func (m *Request) Reset()                    { *m = Request{} }
func (m *Request) String() string            { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()               {}
func (*Request) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Request) GetAgentID() string {
	if m != nil {
		return m.AgentID
	}
	return ""
}

// Regiters user and agent
type Setup struct {
	Token     string `protobuf:"bytes,1,opt,name=token" json:"token,omitempty"`
	ProductID string `protobuf:"bytes,2,opt,name=productID" json:"productID,omitempty"`
	UserID    string `protobuf:"bytes,3,opt,name=userID" json:"userID,omitempty"`
	Heatrbeat int32  `protobuf:"varint,4,opt,name=heatrbeat" json:"heatrbeat,omitempty"`
}

func (m *Setup) Reset()                    { *m = Setup{} }
func (m *Setup) String() string            { return proto.CompactTextString(m) }
func (*Setup) ProtoMessage()               {}
func (*Setup) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Setup) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *Setup) GetProductID() string {
	if m != nil {
		return m.ProductID
	}
	return ""
}

func (m *Setup) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *Setup) GetHeatrbeat() int32 {
	if m != nil {
		return m.Heatrbeat
	}
	return 0
}

func init() {
	proto.RegisterType((*Agentstate)(nil), "agentState.agentstate")
	proto.RegisterType((*Request)(nil), "agentState.request")
	proto.RegisterType((*Setup)(nil), "agentState.setup")
}

func init() { proto.RegisterFile("agentMessage.protoStruct", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 218 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x90, 0x31, 0x4e, 0xc4, 0x30,
	0x10, 0x45, 0xe5, 0x5d, 0x9c, 0x55, 0x46, 0x54, 0x16, 0x42, 0x2e, 0xb6, 0x58, 0x99, 0x26, 0x15,
	0x0d, 0x57, 0x08, 0x45, 0x0a, 0x9a, 0x70, 0x02, 0x07, 0x46, 0x49, 0x84, 0x14, 0x3b, 0xf6, 0x58,
	0x70, 0x2a, 0xce, 0x88, 0x32, 0x09, 0x0a, 0x96, 0xd8, 0xf2, 0xbd, 0xaf, 0x64, 0xfe, 0x37, 0x28,
	0xdb, 0xe3, 0x44, 0x2f, 0x18, 0xa3, 0xed, 0xf1, 0xd1, 0x07, 0x47, 0x4e, 0x01, 0xbb, 0x57, 0xb2,
	0x84, 0xe6, 0x5b, 0xc0, 0x8a, 0x71, 0x41, 0x75, 0x07, 0x92, 0xdc, 0x07, 0x4e, 0x5a, 0x5c, 0x44,
	0x55, 0xb6, 0x2b, 0xa8, 0x7b, 0x28, 0x52, 0xc4, 0xd0, 0xd4, 0xfa, 0xc0, 0x7a, 0x23, 0xa5, 0xe1,
	0xc4, 0xdf, 0x36, 0xb5, 0x3e, 0x72, 0xf0, 0x8b, 0xea, 0x0c, 0xa5, 0x0f, 0xee, 0x3d, 0xbd, 0x2d,
	0xd9, 0x0d, 0x67, 0xbb, 0x58, 0xfe, 0xf7, 0x89, 0x63, 0x3f, 0x90, 0x96, 0x17, 0x51, 0xc9, 0x76,
	0x23, 0x65, 0xe0, 0x96, 0x6b, 0x3c, 0x7f, 0xf9, 0x31, 0x60, 0xd4, 0x05, 0xa7, 0x99, 0x33, 0x0f,
	0x70, 0x0a, 0x38, 0x27, 0x8c, 0xf4, 0xf7, 0xbc, 0xc8, 0xce, 0x9b, 0x19, 0x64, 0x44, 0x4a, 0xfe,
	0xca, 0x9e, 0xac, 0xdd, 0xe1, 0x9f, 0x76, 0xdb, 0xda, 0x63, 0xb6, 0xf6, 0x0c, 0xe5, 0x80, 0x96,
	0x42, 0x87, 0x96, 0x78, 0x93, 0x6c, 0x77, 0xd1, 0x15, 0xfc, 0xb6, 0x4f, 0x3f, 0x01, 0x00, 0x00,
	0xff, 0xff, 0xda, 0x36, 0xfb, 0xd1, 0x71, 0x01, 0x00, 0x00,
}
