// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protoStruct.proto

/*
Package protoStruct is a generated protocol buffer package.

It is generated from these files:
	protoStruct.proto

It has these top-level messages:
	Agentstate
	Request
	Setup
*/
package protoStruct

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Regular message, that is sent on heartbeat
type Agentstate struct {
	Token        string `protobuf:"bytes,1,opt,name=token" json:"token,omitempty"`
	AgentID      string `protobuf:"bytes,2,opt,name=agentID" json:"agentID,omitempty"`
	User         string `protobuf:"bytes,3,opt,name=user" json:"user,omitempty"`
	Product      string `protobuf:"bytes,4,opt,name=product" json:"product,omitempty"`
	Weight       int32  `protobuf:"varint,5,opt,name=weight" json:"weight,omitempty"`
	StateExpires int64  `protobuf:"varint,6,opt,name=stateExpires" json:"stateExpires,omitempty"`
}

func (m *Agentstate) Reset()                    { *m = Agentstate{} }
func (m *Agentstate) String() string            { return proto.CompactTextString(m) }
func (*Agentstate) ProtoMessage()               {}
func (*Agentstate) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Agentstate) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *Agentstate) GetAgentID() string {
	if m != nil {
		return m.AgentID
	}
	return ""
}

func (m *Agentstate) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

func (m *Agentstate) GetProduct() string {
	if m != nil {
		return m.Product
	}
	return ""
}

func (m *Agentstate) GetWeight() int32 {
	if m != nil {
		return m.Weight
	}
	return 0
}

func (m *Agentstate) GetStateExpires() int64 {
	if m != nil {
		return m.StateExpires
	}
	return 0
}

// Request
type Request struct {
	AgentID string `protobuf:"bytes,1,opt,name=agentID" json:"agentID,omitempty"`
}

func (m *Request) Reset()                    { *m = Request{} }
func (m *Request) String() string            { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()               {}
func (*Request) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Request) GetAgentID() string {
	if m != nil {
		return m.AgentID
	}
	return ""
}

// Setup message is sent by server to configure agent
type Setup struct {
	Token     string `protobuf:"bytes,1,opt,name=token" json:"token,omitempty"`
	ProductID string `protobuf:"bytes,2,opt,name=productID" json:"productID,omitempty"`
	UserID    string `protobuf:"bytes,3,opt,name=userID" json:"userID,omitempty"`
	Heartbeat int32  `protobuf:"varint,4,opt,name=heartbeat" json:"heartbeat,omitempty"`
}

func (m *Setup) Reset()                    { *m = Setup{} }
func (m *Setup) String() string            { return proto.CompactTextString(m) }
func (*Setup) ProtoMessage()               {}
func (*Setup) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Setup) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *Setup) GetProductID() string {
	if m != nil {
		return m.ProductID
	}
	return ""
}

func (m *Setup) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *Setup) GetHeartbeat() int32 {
	if m != nil {
		return m.Heartbeat
	}
	return 0
}

func init() {
	proto.RegisterType((*Agentstate)(nil), "protoStruct.agentstate")
	proto.RegisterType((*Request)(nil), "protoStruct.request")
	proto.RegisterType((*Setup)(nil), "protoStruct.setup")
}

func init() { proto.RegisterFile("protoStruct.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 222 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x90, 0xb1, 0x4e, 0xc3, 0x30,
	0x14, 0x45, 0x65, 0x5a, 0xa7, 0xea, 0x83, 0x05, 0x0b, 0x21, 0x0f, 0x0c, 0x91, 0x59, 0x32, 0xb1,
	0xf0, 0x0b, 0x65, 0xe8, 0x6a, 0xbe, 0xc0, 0x0d, 0x4f, 0x49, 0x84, 0x14, 0x3b, 0xf6, 0xb3, 0xe0,
	0x8b, 0xf8, 0x4e, 0x64, 0xc7, 0x90, 0x64, 0xe8, 0xf6, 0xee, 0xd1, 0x8d, 0x72, 0xae, 0xe1, 0xde,
	0x79, 0x4b, 0xf6, 0x9d, 0x7c, 0x6c, 0xe9, 0x25, 0xdf, 0xe2, 0x76, 0x85, 0xd4, 0x0f, 0x03, 0x30,
	0x1d, 0x8e, 0x14, 0xc8, 0x10, 0x8a, 0x07, 0xe0, 0x64, 0x3f, 0x71, 0x94, 0xac, 0x66, 0xcd, 0x51,
	0xcf, 0x41, 0x48, 0x38, 0xe4, 0xce, 0xf9, 0x24, 0x6f, 0x32, 0xff, 0x8b, 0x42, 0xc0, 0x3e, 0x06,
	0xf4, 0x72, 0x97, 0x71, 0xbe, 0x53, 0xdb, 0x79, 0xfb, 0x11, 0x5b, 0x92, 0xfb, 0xb9, 0x5d, 0xa2,
	0x78, 0x84, 0xea, 0x0b, 0x87, 0xae, 0x27, 0xc9, 0x6b, 0xd6, 0x70, 0x5d, 0x92, 0x50, 0x70, 0x97,
	0x7f, 0xff, 0xf6, 0xed, 0x06, 0x8f, 0x41, 0x56, 0x35, 0x6b, 0x76, 0x7a, 0xc3, 0xd4, 0x33, 0x1c,
	0x3c, 0x4e, 0x11, 0x03, 0xad, 0x75, 0xd8, 0x46, 0x47, 0x4d, 0xc0, 0x03, 0x52, 0x74, 0x57, 0x76,
	0x3c, 0xc1, 0xb1, 0xa8, 0xfc, 0x2f, 0x59, 0x40, 0xb2, 0x4b, 0xfe, 0xe7, 0x53, 0x59, 0x53, 0x52,
	0xfa, 0xaa, 0x47, 0xe3, 0xe9, 0x82, 0x66, 0x5e, 0xc4, 0xf5, 0x02, 0x2e, 0x55, 0x7e, 0xcd, 0xd7,
	0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x01, 0x75, 0xcb, 0xc1, 0x69, 0x01, 0x00, 0x00,
}
